#! /usr/bin/env python3

from ww import Key, Host, Link

inwall_server_ip = "47.94.166.125"
outwall_server_ip = "140.82.21.154"

def yaoyao():
    Key().dump("bj.key")
#    Key().dump("dorm.key")
    Key().dump("lax.key")
    Key().dump("dev1.key")
    Key().dump("dev2.key")
    Key().dump("dev3.key")
    Key().dump("dev4.key")
    Key().dump("dev5.key")
    Key().dump("dev6.key")
    Key().dump("dev7.key")
    Key().dump("dev8.key")

#    dorm_key = Key(key_path="dorm.key")
    lax_key = Key(key_path="lax.key")
    bj_key = Key(key_path="bj.key")
    dev1_key = Key(key_path="dev1.key")
    dev2_key = Key(key_path="dev2.key")
    dev3_key = Key(key_path="dev3.key")
    dev4_key = Key(key_path="dev4.key")
    dev5_key = Key(key_path="dev5.key")
    dev6_key = Key(key_path="dev6.key")
    dev7_key = Key(key_path="dev7.key")
    dev8_key = Key(key_path="dev8.key")

#    dorm = Host("dorm", None, "10.56.100.3", "10.56.233.3", home="/home/louchenyao", key=dorm_key)
    bj = Host("bj", inwall_server_ip, "10.56.100.1", "10.56.233.1", home="/root", key=bj_key)
    #hk = Host("hk", "hk.nossl.cn", "10.56.100.2", "10.56.233.2",home="/home/louchenyao", key=hk_key)
    lax = Host("lax", outwall_server_ip, "10.56.100.4", "10.56.233.4",home="/root", key=lax_key)

    dev1 = Host("dev1", None, None, None, key=dev1_key)
    dev2 = Host("dev2", None, None, None, key=dev2_key)
    dev3 = Host("dev3",None,None,None,key=dev3_key)
    dev4 = Host("dev4",None,None,None,key=dev4_key)
    dev5 = Host("dev5",None,None,None,key=dev5_key)
    dev6 = Host("dev6",None,None,None,key=dev6_key)
    dev7 = Host("dev7",None,None,None,key=dev7_key)
    dev8 = Host("dev8",None,None,None,key=dev8_key)

#    dorm_bj = Link(dorm, bj, mtu=1360)
#    dorm_lax = Link(dorm, lax, mtu=1360)
    lax_bj = Link(lax, bj, mtu=1360)

    dev1_bj = Link(dev1, bj, mtu=1360)
    dev2_bj = Link(dev2, bj, mtu=1360)
    dev3_bj = Link(dev3,bj,mtu=1360)
    dev4_bj = Link(dev4,bj,mtu=1360)
    dev5_bj = Link(dev5,bj,mtu=1360)
    dev6_bj = Link(dev6,bj,mtu=1360)
    dev7_bj = Link(dev7,bj,mtu=1360)
    dev8_bj = Link(dev8,bj,mtu=1360)

    bj.add_route(["10.56.100.0/24", "10.56.200.0/24", "10.56.233.0/24", "10.56.40.0/24", "1.1.1.1",], via=bj.lo_ns_ip, in_ns=False)
    bj.add_route([inwall_server_ip, outwall_server_ip], via="10.233.233.1", in_ns=True)
    bj.add_route([lax.lo_ip, lax.lo_ns_ip, "1.1.1.1"], link=lax_bj, in_ns=True)
#    bj.add_route([dorm.lo_ip, dorm.lo_ns_ip, "10.56.40.0/24",], link=dorm_bj, in_ns=True)

    bj.add_ipset("https://pppublic.oss-cn-beijing.aliyuncs.com/ipsets.txt", in_ns=True)
    bj.add_iptable("mangle", "PREROUTING", "-s 10.56.0.0/16 -m set ! --match-set china_ip dst -m set ! --match-set private_ip dst -j MARK --set-xmark 0x1/0xffffffff", in_ns=True)
    bj.add_cmd(bj.ns_exec + "ip rule add fwmark 0x1 table 100")
    bj.add_cmd(bj.ns_exec + "ip route add default via %s table 100" % lax_bj.left_ip)

#    dorm.add_route(["10.56.100.0/24", "10.56.200.0/24", "10.56.233.0/24"], via=dorm.lo_ns_ip, in_ns=False)
#    dorm.add_route(["39.96.60.177", "89.208.248.29"], via="10.233.233.1", in_ns=True)
#    dorm.add_route([lax.lo_ip, lax.lo_ns_ip, "1.1.1.1"], link=dorm_lax, in_ns=True)
#    dorm.add_route([bj.lo_ip, bj.lo_ns_ip], link=dorm_bj, in_ns=True)
#    dorm.add_route([iPhone_bj.left_ip, mac_bj.left_ip], link=dorm_bj, in_ns=True)
#    dorm.add_route("10.56.40.0/24", via=dorm.lo_ip, in_ns=True)

#    dorm.add_ipset("https://pppublic.oss-cn-beijing.aliyuncs.com/ipsets.txt", in_ns=True)
#    dorm.add_iptable("mangle", "PREROUTING", "-s 10.56.0.0/16 -m set ! --match-set china_ip dst -m set ! --match-set private_ip dst -j MARK --set-xmark 0x1/0xffffffff", in_ns=True)
#    dorm.add_cmd(dorm.ns_exec + "ip rule add fwmark 0x1 table 100")
#    dorm.add_cmd(dorm.ns_exec + "ip route add default via %s table 100" % dorm_lax.right_ip)
    #cmd("iptables -t mangle -A POSTROUTING -o wg0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu")

    lax.add_route(["10.56.100.0/24", "10.56.200.0/24", "10.56.233.0/24", "10.56.40.0/24"], via=lax.lo_ns_ip, in_ns=False)
#    lax.add_route([dorm.lo_ip, dorm.lo_ns_ip, "10.56.40.0/24"], link=dorm_lax, in_ns=True)
    lax.add_route([bj.lo_ip, bj.lo_ns_ip], link=lax_bj, in_ns=True)
    lax.add_route([dev1_bj.left_ip, dev2_bj.left_ip], link=lax_bj, in_ns=True)
    lax.add_route([dev3_bj.left_ip,dev4_bj.left_ip,dev5_bj.left_ip,dev6_bj.left_ip,dev7_bj.left_ip,dev8_bj.left_ip], link=lax_bj, in_ns=True)

    dev1.save_cmds_as_bash("dev1.sh")
    dev2.save_cmds_as_bash("dev2.sh")
    dev3.save_cmds_as_bash("dev3.sh")
    dev4.save_cmds_as_bash("dev4.sh")
    dev5.save_cmds_as_bash("dev5.sh")
    dev6.save_cmds_as_bash("dev6.sh")
    dev7.save_cmds_as_bash("dev7.sh")
    dev8.save_cmds_as_bash("dev8.sh")
#    dorm.save_cmds_as_bash("dorm.sh")
    bj.save_cmds_as_bash("bj.sh")
    lax.save_cmds_as_bash("lax.sh")

if __name__ == "__main__":
    yaoyao()
